# .github/workflows/deploy.yml
name: Deploy Tel Chat to VM

on:
  push:
    branches:
      - main
    paths:
      - 'tel_chat/**'  # Only trigger when files in tel_chat change

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy tel_chat to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "tel_chat/*"  # Only copy tel_chat directory
          target: "/path/on/vm/app"
          
      - name: Restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /path/on/vm/app
            pip install -r tel_chat/requirements.txt
            systemctl restart tel_chat.service