name: Deploy Tel Chat to VM

on:
  push:
    branches:
      - main
    paths:
      - 'tel_chat/**'  # Only trigger when files in tel_chat change
  # Add manual trigger option for testing
  workflow_dispatch:

jobs:
  deploy:
    # This is the key change - using your self-hosted runner instead of GitHub's runners
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy application
        run: |
          echo "Starting deployment at $(date)"
          
          # Copy the application files (keeping .env file intact)
          rsync -av --exclude=".env" tel_chat/ /home/ubuntu/deployments/ai_numb/tel_chat/
          
          # Setup and restart the service
          cd /home/ubuntu/deployments/ai_numb
          source venv/bin/activate
          pip install -r tel_chat/requirements.txt
          
          # Restart the bot service
          sudo systemctl restart numberz-bot
          
          # Verify service status
          sudo systemctl status numberz-bot --no-pager
          
          echo "Deployment completed at $(date)"