name: Deploy Tel Chat to VM

on:
  push:
    branches:
      - main
    paths:
      - 'tel_chat/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy application
        run: |
          echo "Starting deployment at $(date)"
          
          # Debug information
          echo "Current user: $(whoami)"
          echo "Sudo config:"
          sudo -l || echo "Cannot list sudo privileges"
          echo "Systemctl path: $(which systemctl)"
          
          # Copy the application files (keeping .env file intact)
          rsync -av --exclude=".env" tel_chat/ /home/ubuntu/deployments/ai_numb/tel_chat/
          
          # Setup and restart the service
          cd /home/ubuntu/deployments/ai_numb
          source venv/bin/activate
          pip install -r tel_chat/requirements.txt
          
          # Try different approaches to restart the service
          echo "Attempting to restart service..."
          
          # Option 1: Direct systemctl with -n flag
          sudo -n systemctl restart numberz-bot || echo "Failed with sudo -n"
          
          # Option 2: Use full path
          sudo -n $(which systemctl) restart numberz-bot || echo "Failed with full path"
          
          # Check if service is running
          systemctl status numberz-bot --no-pager || echo "Service status check failed"
          
          # Alternative service check
          ps aux | grep "[p]ython.*app.py"
          
          echo "Deployment completed at $(date)"